EasyManagement/EM.Web/Areas/Warehouse/Pages/Index.cshtml.cs
using System.Net;
using EM.DataRepository.Warehouses;
using EM.Helper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace EM.Web.Areas.Warehouse.Pages
{
    public class IndexModel : PageModel
    {
        public IList<ListWarehouses>? Warehouses { get; set; } = new List<ListWarehouses>();

        [BindProperty] public CreateWarehouse CreateWarehouse { get; set; } = new CreateWarehouse();

        [BindProperty] public CreateWarehouse EditWarehouse { get; set; } = new CreateWarehouse();

        public async Task<IActionResult> OnGet()
        {
            var response = await Api.GetApi("Warehouse");

            switch (response.StatusCode)
            {
                case HttpStatusCode.OK:
                    var result = await response.Content.ReadAsStringAsync();
                    Warehouses = JsonConvert.DeserializeObject<IList<ListWarehouses>>(result);
                    return Page();
                case HttpStatusCode.NoContent:
                    return Page();
                default:
                    return Page();
            }
        }

        public async Task<IActionResult> OnGetWarehouseInfoAsync(int id)
        {
            var response = await Api.GetApi("Warehouse/" + id);

            var result = await response.Content.ReadAsStringAsync();

            var warehouseDetails = JsonConvert.DeserializeObject<InfoWarehouse>(result);

            var resultJson = new
            {
                data1 = warehouseDetails?.Id,
                data2 = warehouseDetails?.Name
            };

            return new JsonResult(resultJson);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var response = await Api.PostApi(CreateWarehouse, "Warehouse");

            switch (response.StatusCode)
            {
                case HttpStatusCode.Created:
                    return RedirectToPage();
                default:
                    return Page();
            }
        }

        public async Task<IActionResult> OnPostEditAsync()
        {
            var response = await Api.PutApi(EditWarehouse, "Warehouse");

            switch (response.StatusCode)
            {
                case HttpStatusCode.OK:
                    return RedirectToPage();
                default:
                    return Page();
            }
        }

        public async Task OnGetDeleteAsync(int id)
        {
            await Api.DeleteApi("Warehouse/" + id);
        }
    }
}

EasyManagement/EM.Web/Areas/Warehouse/Pages/Index.cshtml
@page
@model EM.Web.Areas.Warehouse.Pages.IndexModel
@{
    ViewData["Title"] = "Armazéns";
}

@section Styles {
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/datatable/datatables.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/extensions/responsive.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/extensions/colReorder.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/extensions/buttons.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/datatable/buttons.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/extensions/fixedHeader.dataTables.min.css">
    
    <style>
        .dataTables_scrollBody {
            overflow-x: hidden;
        }
    </style>
}

<section id="Armazens">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Armazéns</h4>
                    <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-content collapse show">
                    <div class="card-body card-dashboard">
                        <table id="tableFinish" class="table table-striped" style="width: 100%">
                            <thead>
                            <tr>
                                <th>Identificação</th>
                                <th>Armazém</th>
                                <th>Comandos</th>
                            </tr>
                            </thead>
                        @*<tbody>
                            <tr>
                                <td>1</td>
                                <td>Sede</td>
                                <td>
                                    <a class="btn btn-icon btn-info mr-1 mb-1 waves-effect waves-light" href="/Asset/Detail?id=" data-toggle="tooltip" data-placement="top" title="Detalhes"><i class="la la-info-circle" style="color: white;"></i></a>

                                    <a class="btn btn-icon btn-warning mr-1 mb-1 waves-effect waves-light" href="/Asset/Edit?id=" data-toggle="tooltip" data-placement="top" title="Editar"><i class="la la-edit" style="color: white;"></i></a>

                                    <a class="btn btn-icon btn-danger mr-1 mb-1 waves-effect waves-light btnDeleteAsset" data-id="" data-toggle="tooltip" data-placement="top" title="Eliminar"><i style="color: white;" class="la la-close"></i></a>
                                </td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>Armazém Braga</td>
                                <td>
                                    <a class="btn btn-icon btn-info mr-1 mb-1 waves-effect waves-light" href="/Asset/Detail?id=" data-toggle="tooltip" data-placement="top" title="Detalhes"><i class="la la-info-circle" style="color: white;"></i></a>

                                    <a class="btn btn-icon btn-warning mr-1 mb-1 waves-effect waves-light" href="/Asset/Edit?id=" data-toggle="tooltip" data-placement="top" title="Editar"><i class="la la-edit" style="color: white;"></i></a>

                                    <a class="btn btn-icon btn-danger mr-1 mb-1 waves-effect waves-light btnDeleteAsset" data-id="" data-toggle="tooltip" data-placement="top" title="Eliminar"><i style="color: white;" class="la la-close"></i></a>
                                </td>
                            </tr>
                            </tbody>*@
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="buy-now">
    <a class="btn btn-info btn-glow round px-2" data-toggle="modal" data-target="#createWarehouseModal" style="color: white;">Adicionar Armazem</a>
</div>

<div class="modal fade text-left" id="createWarehouseModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel34" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4> Adicionar Armazém</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: black;">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form" method="post">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-12 col-md-12">
                            <div class="form-group">
                                <label for="nomeCampo">Nome</label>
                                <input asp-for="CreateWarehouse.Nome" type="text" class="form-control input-lg" placeholder="Nome" required />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="reset" class="btn btn-outline-secondary btn-lg" data-dismiss="modal" value="Fechar">
                    <input type="submit" class="btn btn-outline-primary btn-lg" value="Guardar">
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade text-left" id="editWarehouseModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel34" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4> Editar Armazém</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: black;">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form class="form" method="post" asp-page-handler="edit">
				<div class="modal-body">
					<div class="row">
						<div class="col-lg-12 col-md-12">
							<div class="form-group">
								<label>Nome</label>
                                    <input name="EditWarehouse.Name" id="editName" type="text" class="form-control input-lg" placeholder="Nome do Armazém" required />
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<input type="reset" class="btn btn-outline-secondary btn-lg" data-dismiss="modal" value="Fechar">
					<input type="submit" class="btn btn-outline-primary btn-lg" value="Guardar">
				</div>
			</form>
		</div>
	</div>
</div>

@section Scripts {

    <script src="~/app-assets/vendors/js/tables/datatable/datatables.min.js"></script>
    <script src="~/app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js"></script>
    <script src="~/app-assets/vendors/js/tables/buttons.colVis.min.js"></script>
    <script src="~/app-assets/vendors/js/tables/datatable/dataTables.colReorder.min.js"></script>
    <script src="~/app-assets/vendors/js/tables/datatable/dataTables.buttons.min.js"></script>
    <script src="~/app-assets/vendors/js/tables/datatable/buttons.bootstrap4.min.js"></script>
    <script src="~/app-assets/vendors/js/tables/datatable/dataTables.fixedHeader.min.js"></script>
    <script src="~/app-assets/vendors/js/extensions/sweetalert2.all.min.js"></script>
    <script src="~/assets/js/zebra.js"></script>

    <script>

        $(document).ready(function() {
            var data = [];

	        @foreach (var d in Model.Warehouses)
	        {
		        @:data.push(["@d.Id", "@d.Name", "<a class=\"btn btn-icon btn-info mr-1 mb-1 waves-effect waves-light\" href=\"/Asset/Detail?id=@d.Id\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Detalhes\"><i class=\"la la-info-circle\" style=\"color: white;\"></i></a><a class=\"btn btn-icon btn-warning mr-1 mb-1 waves-effect waves-light\" href=\"/Asset/Edit?id=@d.Id\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Editar\"><i class=\"la la-edit\" style=\"color: white;\"></i></a> <a class=\"btn btn-icon btn-danger mr-1 mb-1 waves-effect waves-light btnDeleteAsset\" data-id=\"@d.Id\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Eliminar\"><i style=\"color: white;\" class=\"la la-close\"></i></a> "]);
	        }

            //console.log(data);

            $('#tableFinish').DataTable({
                data:           data,
                deferRender:    true,
                scrollY:        550,
                scrollCollapse: true,
                scroller:       true
            });
        });

        $('.btnEditWarehouse').on('click',
            function (e) {
                var id = $(this).attr('data-id');
                e.preventDefault();
                $.getJSON('Warehouse/WarehouseInfo?id=' + id,
                    function (data) {
                        $('#editName').val(data.data2);
                    });
                e.preventDefault();
            });


        $('.btnDeleteWarehouse').on('click',
            function (e) {
                var id = $(this).attr('data-id');
                Swal.fire({
                    title: 'Tem a certeza?',
                    text: "Não poderá voltar atrás!",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Eliminar!',
                    confirmButtonClass: 'btn btn-primary',
                    cancelButtonClass: 'btn btn-danger ml-1',
                    buttonsStyling: false,
                }).then(function (result) {
                    if (result.value) {
                        $.ajax({
                            type: "GET",
                            url: 'Warehouse/Delete?id=' + id,
                            dataType: "json",
                            contentType: "application/json; charset=utf-8"
                        });
                        Swal.fire({
                            type: "success",
                            title: 'Eliminado!',
                            text: 'Warehouse eliminado com sucesso.',
                            confirmButtonClass: 'btn btn-success'
                        }).then(function (result) {
                            if (result.value) {
                                location.href = 'Warehouse';
                            }
                        });
                    }
                });
            });

        $(document).on('click',
            '.btnDeleteAsset',
            function (e) {
                Swal.fire({
                    title: 'Tem certeza?',
                    text: "Não poderá reverter isso!",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Sim, eliminar!',
                    cancelButtonText: 'Não'
                }).then((result) => {
                    if (result.value) {
                        const id = $(this).attr('data-id');
                        window.location.href = '/AssetFinished?id=' + id + '&handler=Delete';
                    }
                });
            });

        //var element = document.getElementById("finalizados");
        //element.classList.add("active");
    </script>
}